swagger: "2.0"
info:
  description: "This is a sample CRUD API for managing users."
  version: "1.0.0"
  title: "CRUD API"
  contact:
    email: "support@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8000"
basePath: "/api/v1"
tags:
  - name: "users"
    description: "Operations about users"
schemes:
  - "http"
paths:
  /users:
    post:
      tags:
        - "users"
      summary: "Create a new user"
      description: "Create a new user with the input payload"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "user"
          description: "User object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "User created"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    get:
      tags:
        - "users"
      summary: "Get a user by ID"
      description: "Get user details by ID"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  User:
    type: "object"
    required:
      - "id"
      - "name"
      - "email"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"
  ErrorResponse:
    type: "object"
    properties:
      error:
        type: "string"
