version: '3.8'

services:
  app:
    image: asamtech/user-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      - DB_HOST=localhost  
      - DB_PORT=5432 
      - DB_USER=postgres
      - DB_PASSWORD=Admin
      - DB_NAME=CRUD-API
    depends_on:
      - db

  db:
    image: postgres:13 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=CRUD-API
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

volumes:
  db-data:
    driver: local
